<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Daily Sales Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 18px; color: #000; }
        .no-print { margin-bottom: 12px; }
        .btn { display: inline-block; padding: 8px 12px; border: 1px solid #d1d5db; border-radius: 6px; background: #fff; text-decoration: none; font-size: 13px; cursor: pointer; }
        .report-header { margin-bottom: 12px; }
        .report-header-top { display: grid; grid-template-columns: 220px 1fr 320px; align-items: start; gap: 12px; }
        .report-logo { width: 80px; height: 80px; object-fit: contain; display: block; }
        .report-logo-text { font-size: 32px; font-family: "Brush Script MT", cursive; line-height: 1; margin-top: 2px; }
        .report-company { text-align: center; }
        .report-company h1 { margin: 0; font-size: 30px; letter-spacing: 0.3px; }
        .report-company .address { margin-top: 3px; font-size: 20px; }
        .report-company .title { margin-top: 8px; font-size: 33px; font-weight: 700; }
        .report-meta { font-size: 20px; line-height: 1.45; }
        .report-meta .row strong { font-weight: 700; }
        .report-header-bottom { margin-top: 10px; display: flex; justify-content: space-between; gap: 10px; font-size: 20px; }
        .report-header-bottom .left,
        .report-header-bottom .right { width: 49%; }
        .report-header-bottom .row { margin-bottom: 6px; white-space: nowrap; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #cfd3d8; padding: 7px; font-size: 12px; text-align: left; }
        th { background: #f3f4f6; font-weight: 700; }
        .right { text-align: right; }
        @media print { .no-print { display: none !important; } }
    </style>
</head>
<body>
    <div class="no-print">
        <button class="btn" onclick="window.print()">Print</button>
        <a class="btn" href="{{ route('reports.daily-sales') }}">Back to Report</a>
    </div>
    <div class="report-header">
        <div class="report-header-top">
            <div>
                <img class="report-logo" src="{{ asset('logo.png') }}" alt="Layla Kitchen Logo">
                <div class="report-logo-text">Layla Kitchen</div>
            </div>
            <div class="report-company">
                <h1>LAYLA KITCHEN W.L.L</h1>
                <div class="address">MAAMOURA AL MAADID STREET, DOHA, QATAR</div>
                <div class="title">DAILY SALES REPORT</div>
            </div>
            <div class="report-meta">
                <div class="row"><strong>Date & Time</strong> : {{ $generatedAt->format('d-M-Y h:i A') }}</div>
                <div class="row"><strong>Generated By</strong> : {{ $generatedBy ?? '-' }}</div>
            </div>
        </div>
        <div class="report-header-bottom">
            <div class="left">
                <div class="row"><strong>Warehouse</strong> : {{ $warehouse ?? '-' }}</div>
                <div class="row"><strong>Sales Person</strong> : {{ $salesPerson ?? '-' }}</div>
            </div>
            <div class="right">
                <div class="row"><strong>Start Date & Time</strong> : {{ ($startAt ?? now())->format('d-M-Y h:i A') }}</div>
                <div class="row"><strong>End Date & Time</strong> : {{ ($endAt ?? now())->format('d-M-Y h:i A') }}</div>
            </div>
        </div>
    </div>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th class="right">Count</th>
                <th class="right">Total</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($days as $row)
                <tr>
                    <td>{{ $row['date'] }}</td>
                    <td class="right">{{ $row['count'] }}</td>
                    <td class="right">{{ $formatCents($row['total_cents']) }}</td>
                </tr>
            @empty
                <tr><td colspan="3">No sales found.</td></tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
