@php
    use App\Models\Branch;
    use Carbon\Carbon;

    $resolvedGeneratedAt = isset($generatedAt)
        ? ($generatedAt instanceof \DateTimeInterface ? Carbon::instance(\DateTimeImmutable::createFromInterface($generatedAt)) : Carbon::parse((string) $generatedAt))
        : now();
    $resolvedGeneratedBy = (string) ($generatedBy ?? (auth()->user()?->username ?: auth()->user()?->name ?: '-'));
    $resolvedTitle = (string) ($reportTitle ?? 'Report');

    $branchId = request()->integer('branch_id');
    $resolvedWarehouse = (string) ($warehouse ?? ($branchId > 0
        ? (Branch::query()->whereKey($branchId)->value('name') ?: $branchId)
        : 'All Branches'));
    $resolvedSalesPerson = (string) ($salesPerson ?? '-');

    $isMonthly = str_contains(strtolower($resolvedTitle), 'monthly');
    $resolvedStartAt = isset($startAt)
        ? ($startAt instanceof \DateTimeInterface ? Carbon::instance(\DateTimeImmutable::createFromInterface($startAt)) : Carbon::parse((string) $startAt))
        : (request()->filled('date_from')
            ? Carbon::parse((string) request()->input('date_from'))->startOfDay()
            : ($isMonthly ? now()->startOfMonth() : now()->startOfDay()));
    $resolvedEndAt = isset($endAt)
        ? ($endAt instanceof \DateTimeInterface ? Carbon::instance(\DateTimeImmutable::createFromInterface($endAt)) : Carbon::parse((string) $endAt))
        : (request()->filled('date_to')
            ? Carbon::parse((string) request()->input('date_to'))->endOfDay()
            : ($isMonthly ? now()->endOfMonth() : now()->endOfDay()));
@endphp
<div class="report-header">
    <div class="report-header-top">
        <div>
            <img class="report-logo" src="{{ asset('logo.png') }}" alt="Layla Kitchen Logo">
        </div>
        <div class="report-company">
            <h2>LAYLA KITCHEN W.L.L</h2>
            <div class="address">MAAMOURA AL MAADID STREET, DOHA, QATAR</div>
            <div class="title">{{ $resolvedTitle }}</div>
        </div>
        <div class="report-meta">
            <div class="row"><strong>Date & Time</strong> : {{ $resolvedGeneratedAt->format('d-M-Y h:i A') }}</div>
            <div class="row"><strong>Generated By</strong> : {{ $resolvedGeneratedBy }}</div>
        </div>
    </div>
    <div class="report-header-bottom">
        <div class="left">
            <div class="row"><strong>Warehouse</strong> : {{ $resolvedWarehouse }}</div>
            <div class="row"><strong>Sales Person</strong> : {{ $resolvedSalesPerson }}</div>
        </div>
        <div class="right">
            <div class="row"><strong>Start Date & Time</strong> : {{ $resolvedStartAt->format('d-M-Y h:i A') }}</div>
            <div class="row"><strong>End Date & Time</strong> : {{ $resolvedEndAt->format('d-M-Y h:i A') }}</div>
        </div>
    </div>
</div>
