<?php

return [
    'default_locale' => env('HELP_DEFAULT_LOCALE', 'en'),

    'bot' => [
        'enabled' => env('HELP_BOT_ENABLED', true),
        'max_context_items' => (int) env('HELP_BOT_MAX_CONTEXT_ITEMS', 6),
        'session_title_limit' => 80,
    ],

    'modules' => [
        'general' => 'General',
        'orders' => 'Orders',
        'pos' => 'POS',
        'customers' => 'Customers',
        'catalog' => 'Catalog',
        'daily_dish' => 'Daily Dish',
        'subscriptions' => 'Subscriptions',
        'company_food' => 'Company Food',
        'inventory' => 'Inventory',
        'purchasing' => 'Purchasing',
        'receivables' => 'Receivables',
        'spend' => 'Spend',
        'reports' => 'Reports',
    ],

    'capture_scenarios' => [
        'login-and-navigation.dashboard' => [
            'article' => 'login-and-navigation',
            'step' => 1,
            'user' => 'help.manager',
            'route' => 'reports.index',
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => 'main',
            'output' => 'help/login-and-navigation/dashboard.png',
        ],
        'create-and-edit-orders.list' => [
            'article' => 'create-and-edit-orders',
            'step' => 1,
            'user' => 'help.cashier',
            'route' => 'orders.index',
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => 'main',
            'output' => 'help/create-and-edit-orders/list.png',
        ],
        'create-and-edit-orders.form' => [
            'article' => 'create-and-edit-orders',
            'step' => 3,
            'user' => 'help.cashier',
            'route' => 'orders.create',
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => 'main',
            'output' => 'help/create-and-edit-orders/form.png',
        ],
        'pos-install-and-shift.install' => [
            'article' => 'pos-install-and-shift-flow',
            'step' => 2,
            'user' => 'help.cashier',
            'route' => 'settings.pos-terminals',
            'viewport' => ['width' => 1280, 'height' => 900],
            'wait_for' => 'main',
            'output' => 'help/pos-install-and-shift/install.png',
        ],
        'customers.list' => [
            'article' => 'manage-customers',
            'step' => 1,
            'user' => 'help.manager',
            'route' => 'customers.index',
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => 'main',
            'output' => 'help/manage-customers/list.png',
        ],
        'customers.create' => [
            'article' => 'manage-customers',
            'step' => 3,
            'user' => 'help.manager',
            'route' => 'customers.create',
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => 'main',
            'output' => 'help/manage-customers/create.png',
        ],
        'menu-items.list' => [
            'article' => 'manage-menu-items',
            'step' => 1,
            'user' => 'help.manager',
            'route' => 'menu-items.index',
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => 'main',
            'output' => 'help/manage-menu-items/list.png',
        ],
        'menu-items.create' => [
            'article' => 'manage-menu-items',
            'step' => 3,
            'user' => 'help.manager',
            'route' => 'menu-items.create',
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => 'main',
            'output' => 'help/manage-menu-items/create.png',
        ],
        'daily-dish.index' => [
            'article' => 'publish-and-clone-daily-dish-menus',
            'step' => 1,
            'user' => 'help.manager',
            'route' => 'daily-dish.menus.index',
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => 'main',
            'output' => 'help/daily-dish/index.png',
        ],
        'inventory.index' => [
            'article' => 'inventory-items-and-stock-adjustments',
            'step' => 1,
            'user' => 'help.manager',
            'route' => 'inventory.index',
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => 'main',
            'output' => 'help/inventory/index.png',
        ],
        'inventory.transfers' => [
            'article' => 'inventory-transfers',
            'step' => 1,
            'user' => 'help.manager',
            'route' => 'inventory.transfers',
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => 'main',
            'output' => 'help/inventory/transfers.png',
        ],
        'purchase-orders.index' => [
            'article' => 'purchase-orders-workflow',
            'step' => 1,
            'user' => 'help.manager',
            'route' => 'purchase-orders.index',
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => 'main',
            'output' => 'help/purchase-orders/index.png',
        ],
        'purchase-orders.create' => [
            'article' => 'purchase-orders-workflow',
            'step' => 3,
            'user' => 'help.manager',
            'route' => 'purchase-orders.create',
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => 'main',
            'output' => 'help/purchase-orders/create.png',
        ],
        'receivables.invoices' => [
            'article' => 'ar-invoices-and-customer-payments',
            'step' => 1,
            'user' => 'help.manager',
            'route' => 'invoices.index',
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => 'main',
            'output' => 'help/receivables/invoices.png',
        ],
        'spend.index' => [
            'article' => 'submit-and-process-spend-requests',
            'step' => 1,
            'user' => 'help.staff',
            'route' => 'spend.index',
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => 'main',
            'output' => 'help/spend/index.png',
        ],
        'reports.index' => [
            'article' => 'run-and-export-reports',
            'step' => 1,
            'user' => 'help.staff',
            'route' => 'reports.index',
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => 'main',
            'output' => 'help/reports/index.png',
        ],
        'recipes.index' => [
            'article' => 'recipe-crud-and-production',
            'step' => 1,
            'user' => 'help.manager',
            'route' => 'recipes.index',
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => ['text=Recipes', 'text=New Recipe'],
            'output' => 'help/recipes/index.png',
        ],
        'recipes.create' => [
            'article' => 'recipe-crud-and-production',
            'step' => 2,
            'user' => 'help.manager',
            'route' => 'recipes.create',
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => ['text=Create Recipe', 'text=Ingredients'],
            'output' => 'help/recipes/create.png',
        ],
        'recipes.show' => [
            'article' => 'recipe-crud-and-production',
            'step' => 3,
            'user' => 'help.manager',
            'route' => 'recipes.show',
            'route_params' => [
                'recipe' => [
                    'lookup_model' => \App\Models\Recipe::class,
                    'lookup_column' => 'name',
                    'lookup_value' => 'Help Citrus Chicken Bowl',
                    'route_key' => 'id',
                ],
            ],
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => ['text=Help Citrus Chicken Bowl', 'text=Ingredients'],
            'output' => 'help/recipes/show.png',
        ],
        'recipes.produce' => [
            'article' => 'recipe-crud-and-production',
            'step' => 4,
            'user' => 'help.manager',
            'route' => 'recipes.index',
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => ['text=Recipes', 'text=Produce'],
            'actions' => [
                [
                    'type' => 'click',
                    'selector' => 'text=Produce',
                    'wait_for' => ['text=Produce Recipe', 'text=Produced Quantity'],
                ],
            ],
            'output' => 'help/recipes/produce.png',
        ],
        'meal-plan-requests.index' => [
            'article' => 'meal-plan-requests-review-and-conversion',
            'step' => 1,
            'user' => 'help.manager',
            'route' => 'meal-plan-requests.index',
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => ['text=Meal Plan Requests', 'text=Contacted'],
            'output' => 'help/meal-plan-requests/index.png',
        ],
        'meal-plan-requests.show' => [
            'article' => 'meal-plan-requests-review-and-conversion',
            'step' => 2,
            'user' => 'help.manager',
            'route' => 'meal-plan-requests.show',
            'route_params' => [
                'mealPlanRequest' => [
                    'lookup_model' => \App\Models\MealPlanRequest::class,
                    'lookup_column' => 'customer_name',
                    'lookup_value' => 'Help Meal Plan Prospect',
                    'route_key' => 'id',
                ],
            ],
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => ['text=Meal Plan Request', 'text=Related Orders'],
            'output' => 'help/meal-plan-requests/show.png',
        ],
        'meal-plan-requests.convert' => [
            'enabled' => false,
            'article' => 'meal-plan-requests-review-and-conversion',
            'step' => 3,
            'user' => 'help.manager',
            'route' => 'meal-plan-requests.index',
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => ['text=Meal Plan Requests', 'text=Converted'],
            'actions' => [
                [
                    'type' => 'click',
                    'selector' => 'button:has-text("Converted")',
                    'wait_for' => ['text=Convert to Subscription', 'text=Existing customer'],
                ],
            ],
            'output' => 'help/meal-plan-requests/convert.png',
        ],
        'subscriptions.index' => [
            'article' => 'meal-subscriptions-lifecycle',
            'step' => 1,
            'user' => 'help.manager',
            'route' => 'subscriptions.index',
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => ['text=Meal Subscriptions', 'text=New Subscription'],
            'output' => 'help/subscriptions/index.png',
        ],
        'subscriptions.create' => [
            'article' => 'meal-subscriptions-lifecycle',
            'step' => 2,
            'user' => 'help.manager',
            'route' => 'subscriptions.create',
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => ['text=Create Subscription', 'text=Weekdays'],
            'output' => 'help/subscriptions/create.png',
        ],
        'subscriptions.show' => [
            'article' => 'meal-subscriptions-lifecycle',
            'step' => 3,
            'user' => 'help.manager',
            'route' => 'subscriptions.show',
            'route_params' => [
                'subscription' => [
                    'lookup_model' => \App\Models\MealSubscription::class,
                    'lookup_column' => 'subscription_code',
                    'lookup_value' => 'HELP-SUB-001',
                    'route_key' => 'id',
                ],
            ],
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => ['text=HELP-SUB-001', 'text=Schedule (Weekdays)'],
            'output' => 'help/subscriptions/show.png',
        ],
        'subscriptions.generate' => [
            'article' => 'meal-subscriptions-lifecycle',
            'step' => 4,
            'user' => 'help.manager',
            'route' => 'subscriptions.generate',
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => ['text=Generate Subscription Orders', 'text=Generate'],
            'output' => 'help/subscriptions/generate.png',
        ],
        'company-food.projects.index' => [
            'article' => 'company-food-project-administration',
            'step' => 1,
            'user' => 'help.manager',
            'route' => 'company-food.projects.index',
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => ['text=Company Food Projects', 'text=New Project'],
            'output' => 'help/company-food/index.png',
        ],
        'company-food.projects.create' => [
            'article' => 'company-food-project-administration',
            'step' => 2,
            'user' => 'help.manager',
            'route' => 'company-food.projects.create',
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => ['text=Create Company Food Project', 'text=Slug (for API URL)'],
            'output' => 'help/company-food/create.png',
        ],
        'company-food.projects.show-orders' => [
            'article' => 'company-food-project-administration',
            'step' => 3,
            'user' => 'help.manager',
            'route' => 'company-food.projects.show',
            'route_params' => [
                'project' => [
                    'lookup_model' => \App\Models\CompanyFoodProject::class,
                    'lookup_column' => 'slug',
                    'lookup_value' => 'help-company-food',
                    'route_key' => 'id',
                ],
            ],
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => ['text=Orders', 'text=Employee Orders PDF'],
            'output' => 'help/company-food/show-orders.png',
        ],
        'company-food.projects.menu' => [
            'article' => 'company-food-project-administration',
            'step' => 4,
            'user' => 'help.manager',
            'route' => 'company-food.projects.show',
            'route_params' => [
                'project' => [
                    'lookup_model' => \App\Models\CompanyFoodProject::class,
                    'lookup_column' => 'slug',
                    'lookup_value' => 'help-company-food',
                    'route_key' => 'id',
                ],
            ],
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => ['text=Orders', 'text=Menu'],
            'actions' => [
                [
                    'type' => 'click',
                    'selector' => '[role="radio"]:has-text("Menu")',
                    'wait_for' => ['text=Click a day to add menu options', 'text=18 Feb'],
                ],
                [
                    'type' => 'click',
                    'selector' => '[wire\\:click^="openMenuDrawer("]',
                    'wait_for' => ['text=Company Food Menu', 'text=Add to all days'],
                ],
            ],
            'output' => 'help/company-food/menu.png',
        ],
        'company-food.projects.lists' => [
            'article' => 'company-food-project-administration',
            'step' => 5,
            'user' => 'help.manager',
            'route' => 'company-food.projects.show',
            'route_params' => [
                'project' => [
                    'lookup_model' => \App\Models\CompanyFoodProject::class,
                    'lookup_column' => 'slug',
                    'lookup_value' => 'help-company-food',
                    'route_key' => 'id',
                ],
            ],
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => ['text=Orders', 'text=Lists'],
            'actions' => [
                [
                    'type' => 'click',
                    'selector' => '[role="radio"]:has-text("Lists")',
                    'wait_for' => ['text=Add / Import Employees', 'text=Employees'],
                ],
            ],
            'output' => 'help/company-food/lists.png',
        ],
        'company-food.projects.edit' => [
            'article' => 'company-food-project-administration',
            'step' => 6,
            'user' => 'help.manager',
            'route' => 'company-food.projects.edit',
            'route_params' => [
                'project' => [
                    'lookup_model' => \App\Models\CompanyFoodProject::class,
                    'lookup_column' => 'slug',
                    'lookup_value' => 'help-company-food',
                    'route_key' => 'id',
                ],
            ],
            'viewport' => ['width' => 1440, 'height' => 960],
            'wait_for' => ['text=Edit Company Food Project', 'text=Slug'],
            'output' => 'help/company-food/edit.png',
        ],
    ],
];
