<?php

return [
    'accounts' => [
        'cash' => ['code' => '1000', 'name' => 'Cash', 'type' => 'asset'],
        'bank_operating' => ['code' => '1010', 'name' => 'Operating Bank', 'type' => 'asset'],
        'card_clearing' => ['code' => '1020', 'name' => 'Card Clearing', 'type' => 'asset'],
        'cheque_clearing' => ['code' => '1030', 'name' => 'Cheque Clearing', 'type' => 'asset'],
        'other_clearing' => ['code' => '1040', 'name' => 'Other Clearing', 'type' => 'asset'],
        'petty_cash_asset' => ['code' => '1100', 'name' => 'Petty Cash', 'type' => 'asset'],
        'inventory_asset' => ['code' => '1200', 'name' => 'Inventory', 'type' => 'asset'],
        'ap_prepay' => ['code' => '1300', 'name' => 'Supplier Advances', 'type' => 'asset'],
        'tax_input' => ['code' => '1400', 'name' => 'Input Tax', 'type' => 'asset'],
        'ar_control' => ['code' => '1500', 'name' => 'Accounts Receivable', 'type' => 'asset'],
        'employee_advances_receivable' => ['code' => '1600', 'name' => 'Employee Advances', 'type' => 'asset'],
        'ap_control' => ['code' => '2000', 'name' => 'Accounts Payable', 'type' => 'liability'],
        'grni' => ['code' => '2100', 'name' => 'GRNI Clearing', 'type' => 'liability'],
        'customer_advances' => ['code' => '2200', 'name' => 'Customer Advances', 'type' => 'liability'],
        'tax_output' => ['code' => '2300', 'name' => 'Output Tax', 'type' => 'liability'],
        'payroll_payable' => ['code' => '2400', 'name' => 'Payroll Payable', 'type' => 'liability'],
        'payroll_deductions_payable' => ['code' => '2410', 'name' => 'Payroll Deductions Payable', 'type' => 'liability'],
        'sales_revenue' => ['code' => '4000', 'name' => 'Sales Revenue', 'type' => 'income'],
        'cogs' => ['code' => '5000', 'name' => 'COGS', 'type' => 'expense'],
        'inventory_adjustment' => ['code' => '5100', 'name' => 'Inventory Adjustments', 'type' => 'expense'],
        'petty_cash_over_short' => ['code' => '5200', 'name' => 'Petty Cash Over/Short', 'type' => 'expense'],
        'expense_default' => ['code' => '6000', 'name' => 'General Expense', 'type' => 'expense'],
        'payroll_basic_expense' => ['code' => '6100', 'name' => 'Basic Salary Expense', 'type' => 'expense'],
        'payroll_allowance_expense' => ['code' => '6110', 'name' => 'Payroll Allowance Expense', 'type' => 'expense'],
        'payroll_overtime_expense' => ['code' => '6120', 'name' => 'Payroll Overtime Expense', 'type' => 'expense'],
        'payroll_bonus_expense' => ['code' => '6130', 'name' => 'Payroll Bonus Expense', 'type' => 'expense'],
    ],
    'mappings' => [
        'ap_invoice_expense' => 'expense_default',
        'ap_invoice_inventory' => 'inventory_asset',
        'ap_invoice_ap' => 'ap_control',
        'ap_invoice_tax' => 'tax_input',
        'inventory_asset' => 'inventory_asset',
        'inventory_clearing' => 'grni',
        'inventory_adjustment' => 'inventory_adjustment',
        'inventory_cogs' => 'cogs',
        'ap_payment_cash' => 'cash',
        'ap_payment_prepay' => 'ap_prepay',
        'ar_invoice_ar' => 'ar_control',
        'ar_invoice_revenue' => 'sales_revenue',
        'ar_invoice_tax' => 'tax_output',
        'ar_payment_cash' => 'cash',
        'ar_payment_advance' => 'customer_advances',
        'expense_cash' => 'cash',
        'petty_cash_asset' => 'petty_cash_asset',
        'petty_cash_issue_cash' => 'cash',
        'petty_cash_issue_card' => 'card_clearing',
        'petty_cash_issue_cheque' => 'cheque_clearing',
        'petty_cash_issue_other' => 'other_clearing',
        'petty_cash_expense' => 'expense_default',
        'petty_cash_over_short' => 'petty_cash_over_short',
        'ap_payment_card' => 'card_clearing',
        'ar_payment_card' => 'card_clearing',
        'ap_payment_cheque' => 'cheque_clearing',
        'ar_payment_cheque' => 'cheque_clearing',
        'ap_payment_other' => 'other_clearing',
        'ar_payment_other' => 'other_clearing',
        'payroll_basic_expense' => 'payroll_basic_expense',
        'payroll_allowance_expense' => 'payroll_allowance_expense',
        'payroll_overtime_expense' => 'payroll_overtime_expense',
        'payroll_bonus_expense' => 'payroll_bonus_expense',
        'payroll_payable' => 'payroll_payable',
        'payroll_deductions_payable' => 'payroll_deductions_payable',
        'employee_advances_receivable' => 'employee_advances_receivable',
    ],
];
