<?php

return [
    'categories' => [
        'sales' => [
            'key' => 'sales',
            'label' => 'Sales',
        ],
        'accounts' => [
            'key' => 'accounts',
            'label' => 'Accounts',
        ],
        'purchase_orders' => [
            'key' => 'purchase_orders',
            'label' => 'Purchase Orders',
        ],
        'expenses' => [
            'key' => 'expenses',
            'label' => 'Expenses',
        ],
        'subscriptions' => [
            'key' => 'subscriptions',
            'label' => 'Subscriptions',
        ],
        'accounting' => [
            'key' => 'accounting',
            'label' => 'Accounting',
        ],
    ],

    'reports' => [
        'orders' => [
            'key' => 'orders',
            'label' => 'Orders',
            'category' => 'sales',
            'route' => 'reports.orders',
            'filters' => ['branch', 'status', 'source', 'date', 'search'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'purchase-order-detail' => [
            'key' => 'purchase-order-detail',
            'label' => 'Purchase Order Detail',
            'category' => 'purchase_orders',
            'route' => 'reports.purchase-order-detail',
            'filters' => ['supplier', 'status', 'date_range', 'search'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'purchase-order-receiving' => [
            'key' => 'purchase-order-receiving',
            'label' => 'Purchase Order Receiving',
            'category' => 'purchase_orders',
            'route' => 'reports.purchase-order-receiving',
            'filters' => ['supplier', 'po', 'item', 'date_range', 'receiver'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'purchase-orders' => [
            'key' => 'purchase-orders',
            'label' => 'Purchase Orders',
            'category' => 'purchase_orders',
            'route' => 'reports.purchase-orders',
            'filters' => ['supplier', 'status', 'date_range', 'search'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'supplier-purchases' => [
            'key' => 'supplier-purchases',
            'label' => 'Supplier Purchases',
            'category' => 'purchase_orders',
            'route' => 'reports.supplier-purchases',
            'filters' => ['supplier', 'item', 'date_range', 'status'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'expenses' => [
            'key' => 'expenses',
            'label' => 'Expenses',
            'category' => 'expenses',
            'route' => 'reports.expenses',
            'filters' => ['supplier', 'category', 'payment_status', 'date_range', 'search'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'costing' => [
            'key' => 'costing',
            'label' => 'Costing',
            'category' => 'expenses',
            'route' => 'reports.costing',
            'filters' => ['menu_item', 'category'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'inventory' => [
            'key' => 'inventory',
            'label' => 'Inventory',
            'category' => 'expenses',
            'route' => 'reports.inventory',
            'filters' => ['branch', 'category', 'search', 'low_stock'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'inventory-transactions' => [
            'key' => 'inventory-transactions',
            'label' => 'Inventory Transactions',
            'category' => 'expenses',
            'route' => 'reports.inventory-transactions',
            'filters' => ['branch', 'item', 'supplier', 'category', 'transaction_type', 'reference_type', 'date_range', 'search'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'sales' => [
            'key' => 'sales',
            'label' => 'Sales',
            'category' => 'sales',
            'route' => 'reports.sales',
            'filters' => ['branch', 'status', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'payables' => [
            'key' => 'payables',
            'label' => 'Payables (AP)',
            'category' => 'accounts',
            'route' => 'reports.payables',
            'filters' => ['aging', 'invoice_register', 'payment_register', 'supplier', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'receivables' => [
            'key' => 'receivables',
            'label' => 'Receivables (AR)',
            'category' => 'accounts',
            'route' => 'reports.receivables',
            'filters' => ['branch', 'customer', 'status', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'customer-advances' => [
            'key' => 'customer-advances',
            'label' => 'Advance Payments',
            'category' => 'accounts',
            'route' => 'reports.customer-advances',
            'filters' => ['branch', 'customer', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'session-branch-sales' => [
            'key' => 'session-branch-sales',
            'label' => 'Session Wise Branch Sales Summary',
            'category' => 'sales',
            'route' => 'reports.session-branch-sales',
            'filters' => ['branch', 'cashier', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'daily-sales' => [
            'key' => 'daily-sales',
            'label' => 'Daily Sales Report (All Branches)',
            'category' => 'sales',
            'route' => 'reports.daily-sales',
            'filters' => ['branch', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'sales-entry-daily' => [
            'key' => 'sales-entry-daily',
            'label' => 'Sales Entry Report (Daily)',
            'category' => 'sales',
            'route' => 'reports.sales-entry-daily',
            'filters' => ['branch', 'customer', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'sales-entry-monthly' => [
            'key' => 'sales-entry-monthly',
            'label' => 'Sales Entry Report (Monthly)',
            'category' => 'sales',
            'route' => 'reports.sales-entry-monthly',
            'filters' => ['branch', 'customer', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'category-sales-summary' => [
            'key' => 'category-sales-summary',
            'label' => 'Category Wise Sales Summary',
            'category' => 'sales',
            'route' => 'reports.category-sales-summary',
            'filters' => ['branch', 'category', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'customer-statement' => [
            'key' => 'customer-statement',
            'label' => 'Customer Statement',
            'category' => 'accounts',
            'route' => 'reports.customer-statement',
            'filters' => ['branch', 'customer', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'customers-statement' => [
            'key' => 'customers-statement',
            'label' => 'All Customers Statement',
            'category' => 'accounts',
            'route' => 'reports.customers-statement',
            'filters' => ['branch', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'supplier-statement' => [
            'key' => 'supplier-statement',
            'label' => 'Supplier Statement',
            'category' => 'accounts',
            'route' => 'reports.supplier-statement',
            'filters' => ['supplier', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'suppliers-statement' => [
            'key' => 'suppliers-statement',
            'label' => 'All Suppliers Statement',
            'category' => 'accounts',
            'route' => 'reports.suppliers-statement',
            'filters' => ['date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'payables-summary' => [
            'key' => 'payables-summary',
            'label' => 'Payables Summary',
            'category' => 'accounts',
            'route' => 'reports.payables-summary',
            'filters' => ['date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'customer-aging-summary' => [
            'key' => 'customer-aging-summary',
            'label' => 'Customer Aging Summary',
            'category' => 'accounts',
            'route' => 'reports.customer-aging-summary',
            'filters' => ['branch', 'customer', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'supplier-aging-summary' => [
            'key' => 'supplier-aging-summary',
            'label' => 'Supplier Aging Summary',
            'category' => 'accounts',
            'route' => 'reports.supplier-aging-summary',
            'filters' => ['supplier', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'subscription-details' => [
            'key' => 'subscription-details',
            'label' => 'Subscription Details',
            'category' => 'subscriptions',
            'route' => 'reports.subscription-details',
            'filters' => ['customer', 'status', 'date_range', 'branch'],
            'outputs' => ['screen', 'print', 'csv'],
        ],
        'accounting-trial-balance' => [
            'key' => 'accounting-trial-balance',
            'label' => 'Trial Balance',
            'category' => 'accounting',
            'route' => 'reports.accounting-trial-balance',
            'filters' => ['company', 'as_of'],
            'outputs' => ['screen'],
        ],
        'accounting-profit-loss' => [
            'key' => 'accounting-profit-loss',
            'label' => 'Profit & Loss',
            'category' => 'accounting',
            'route' => 'reports.accounting-profit-loss',
            'filters' => ['company', 'as_of'],
            'outputs' => ['screen'],
        ],
        'accounting-balance-sheet' => [
            'key' => 'accounting-balance-sheet',
            'label' => 'Balance Sheet',
            'category' => 'accounting',
            'route' => 'reports.accounting-balance-sheet',
            'filters' => ['company', 'as_of'],
            'outputs' => ['screen'],
        ],
        'accounting-cash-flow' => [
            'key' => 'accounting-cash-flow',
            'label' => 'Cash Flow',
            'category' => 'accounting',
            'route' => 'reports.accounting-cash-flow',
            'filters' => ['company', 'as_of'],
            'outputs' => ['screen'],
        ],
        'accounting-bank-reconciliation' => [
            'key' => 'accounting-bank-reconciliation',
            'label' => 'Bank Reconciliation Summary',
            'category' => 'accounting',
            'route' => 'reports.accounting-bank-reconciliation',
            'filters' => ['company', 'as_of'],
            'outputs' => ['screen'],
        ],
        'accounting-budget-variance' => [
            'key' => 'accounting-budget-variance',
            'label' => 'Budget Variance',
            'category' => 'accounting',
            'route' => 'reports.accounting-budget-variance',
            'filters' => ['company', 'fiscal_year', 'as_of'],
            'outputs' => ['screen'],
        ],
        'accounting-job-profitability' => [
            'key' => 'accounting-job-profitability',
            'label' => 'Job Profitability',
            'category' => 'accounting',
            'route' => 'reports.accounting-job-profitability',
            'filters' => ['company', 'job', 'as_of'],
            'outputs' => ['screen'],
        ],
        'accounting-ap-aging' => [
            'key' => 'accounting-ap-aging',
            'label' => 'AP Aging',
            'category' => 'accounting',
            'route' => 'reports.accounting-ap-aging',
            'filters' => ['company', 'branch', 'department', 'job', 'supplier', 'as_of'],
            'outputs' => ['screen', 'csv'],
        ],
        'accounting-vendor-ledger' => [
            'key' => 'accounting-vendor-ledger',
            'label' => 'Vendor Ledger',
            'category' => 'accounting',
            'route' => 'reports.accounting-vendor-ledger',
            'filters' => ['company', 'branch', 'department', 'job', 'supplier', 'date_range'],
            'outputs' => ['screen', 'csv'],
        ],
        'accounting-expense-analysis' => [
            'key' => 'accounting-expense-analysis',
            'label' => 'Expense Analysis',
            'category' => 'accounting',
            'route' => 'reports.accounting-expense-analysis',
            'filters' => ['company', 'branch', 'department', 'job', 'supplier', 'category', 'payment_status', 'date_range', 'search'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'accounting-inventory-valuation' => [
            'key' => 'accounting-inventory-valuation',
            'label' => 'Inventory Valuation',
            'category' => 'accounting',
            'route' => 'reports.accounting-inventory-valuation',
            'filters' => ['company', 'branch', 'as_of'],
            'outputs' => ['screen', 'csv'],
        ],
        'accounting-purchase-accruals' => [
            'key' => 'accounting-purchase-accruals',
            'label' => 'Purchase Accruals',
            'category' => 'accounting',
            'route' => 'reports.accounting-purchase-accruals',
            'filters' => ['company', 'supplier', 'date_range'],
            'outputs' => ['screen', 'csv'],
        ],
        'accounting-multi-company-summary' => [
            'key' => 'accounting-multi-company-summary',
            'label' => 'Multi-Company Summary',
            'category' => 'accounting',
            'route' => 'reports.accounting-multi-company-summary',
            'filters' => ['as_of'],
            'outputs' => ['screen', 'csv'],
        ],
    ],

    'customer_statement' => [
        'bank_details' => [
            'account_name' => 'LAYLA KITCHEN W.L.L',
            'bank_name' => 'Qatar Islamic Bank',
            'bank_address' => '',
            'account_no' => '',
            'iban' => '',
            'swift_code' => '',
        ],
    ],
];
