<?php

return [
    'categories' => [
        'sales' => [
            'key' => 'sales',
            'label' => 'Sales',
        ],
        'accounts' => [
            'key' => 'accounts',
            'label' => 'Accounts',
        ],
        'purchase_orders' => [
            'key' => 'purchase_orders',
            'label' => 'Purchase Orders',
        ],
        'expenses' => [
            'key' => 'expenses',
            'label' => 'Expenses',
        ],
        'subscriptions' => [
            'key' => 'subscriptions',
            'label' => 'Subscriptions',
        ],
    ],

    'reports' => [
        'orders' => [
            'key' => 'orders',
            'label' => 'Orders',
            'category' => 'sales',
            'route' => 'reports.orders',
            'filters' => ['branch', 'status', 'source', 'date', 'search'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'purchase-order-detail' => [
            'key' => 'purchase-order-detail',
            'label' => 'Purchase Order Detail',
            'category' => 'purchase_orders',
            'route' => 'reports.purchase-order-detail',
            'filters' => ['supplier', 'status', 'date_range', 'search'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'purchase-orders' => [
            'key' => 'purchase-orders',
            'label' => 'Purchase Orders',
            'category' => 'purchase_orders',
            'route' => 'reports.purchase-orders',
            'filters' => ['supplier', 'status', 'date_range', 'search'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'expenses' => [
            'key' => 'expenses',
            'label' => 'Expenses',
            'category' => 'expenses',
            'route' => 'reports.expenses',
            'filters' => ['supplier', 'category', 'payment_status', 'date_range', 'search'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'costing' => [
            'key' => 'costing',
            'label' => 'Costing',
            'category' => 'expenses',
            'route' => 'reports.costing',
            'filters' => ['menu_item', 'category'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'inventory' => [
            'key' => 'inventory',
            'label' => 'Inventory',
            'category' => 'expenses',
            'route' => 'reports.inventory',
            'filters' => ['branch', 'category', 'search', 'low_stock'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'sales' => [
            'key' => 'sales',
            'label' => 'Sales',
            'category' => 'sales',
            'route' => 'reports.sales',
            'filters' => ['branch', 'status', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'payables' => [
            'key' => 'payables',
            'label' => 'Payables (AP)',
            'category' => 'accounts',
            'route' => 'reports.payables',
            'filters' => ['aging', 'invoice_register', 'payment_register', 'supplier', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'receivables' => [
            'key' => 'receivables',
            'label' => 'Receivables (AR)',
            'category' => 'accounts',
            'route' => 'reports.receivables',
            'filters' => ['branch', 'customer', 'status', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'customer-advances' => [
            'key' => 'customer-advances',
            'label' => 'Customer Advances',
            'category' => 'accounts',
            'route' => 'reports.customer-advances',
            'filters' => ['branch', 'customer', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'sales-all' => [
            'key' => 'sales-all',
            'label' => 'Sales Report (All Branches)',
            'category' => 'sales',
            'route' => 'reports.sales-all',
            'filters' => ['branch', 'date_range', 'customer'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'session-branch-sales' => [
            'key' => 'session-branch-sales',
            'label' => 'Session Wise Branch Sales Summary',
            'category' => 'sales',
            'route' => 'reports.session-branch-sales',
            'filters' => ['branch', 'cashier', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'daily-sales' => [
            'key' => 'daily-sales',
            'label' => 'Daily Sales Report (All Branches)',
            'category' => 'sales',
            'route' => 'reports.daily-sales',
            'filters' => ['branch', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'sales-entry-daily' => [
            'key' => 'sales-entry-daily',
            'label' => 'Sales Entry Report (Daily)',
            'category' => 'sales',
            'route' => 'reports.sales-entry-daily',
            'filters' => ['branch', 'customer', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'sales-entry-monthly' => [
            'key' => 'sales-entry-monthly',
            'label' => 'Sales Entry Report (Monthly)',
            'category' => 'sales',
            'route' => 'reports.sales-entry-monthly',
            'filters' => ['branch', 'customer', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'category-sales-summary' => [
            'key' => 'category-sales-summary',
            'label' => 'Category Wise Sales Summary',
            'category' => 'sales',
            'route' => 'reports.category-sales-summary',
            'filters' => ['branch', 'category', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'monthly-branch-sales' => [
            'key' => 'monthly-branch-sales',
            'label' => 'Monthly Branch Wise Sales Report',
            'category' => 'sales',
            'route' => 'reports.monthly-branch-sales',
            'filters' => ['date_range', 'branch'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'receivables-summary' => [
            'key' => 'receivables-summary',
            'label' => 'Receivables Summary',
            'category' => 'accounts',
            'route' => 'reports.receivables-summary',
            'filters' => ['branch', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'customer-statement' => [
            'key' => 'customer-statement',
            'label' => 'Customer Statement',
            'category' => 'accounts',
            'route' => 'reports.customer-statement',
            'filters' => ['branch', 'customer', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'customers-statement' => [
            'key' => 'customers-statement',
            'label' => 'All Customers Statement',
            'category' => 'accounts',
            'route' => 'reports.customers-statement',
            'filters' => ['branch', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'statement-of-accounts' => [
            'key' => 'statement-of-accounts',
            'label' => 'Statement of Accounts',
            'category' => 'accounts',
            'route' => 'reports.statement-of-accounts',
            'filters' => ['branch', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'supplier-statement' => [
            'key' => 'supplier-statement',
            'label' => 'Supplier Statement',
            'category' => 'accounts',
            'route' => 'reports.supplier-statement',
            'filters' => ['supplier', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'suppliers-statement' => [
            'key' => 'suppliers-statement',
            'label' => 'All Suppliers Statement',
            'category' => 'accounts',
            'route' => 'reports.suppliers-statement',
            'filters' => ['date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'payables-summary' => [
            'key' => 'payables-summary',
            'label' => 'Payables Summary',
            'category' => 'accounts',
            'route' => 'reports.payables-summary',
            'filters' => ['date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'customer-aging-summary' => [
            'key' => 'customer-aging-summary',
            'label' => 'Customer Aging Summary',
            'category' => 'accounts',
            'route' => 'reports.customer-aging-summary',
            'filters' => ['branch', 'customer', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'supplier-aging-summary' => [
            'key' => 'supplier-aging-summary',
            'label' => 'Supplier Aging Summary',
            'category' => 'accounts',
            'route' => 'reports.supplier-aging-summary',
            'filters' => ['supplier', 'date_range'],
            'outputs' => ['screen', 'print', 'csv', 'pdf'],
        ],
        'subscription-details' => [
            'key' => 'subscription-details',
            'label' => 'Subscription Details',
            'category' => 'subscriptions',
            'route' => 'reports.subscription-details',
            'filters' => ['customer', 'status', 'date_range', 'branch'],
            'outputs' => ['screen', 'print', 'csv'],
        ],
    ],
];
