server {
    listen 80;
    listen [::]:80;
    server_name rms-dev.34-156-128-236.sslip.io orders-dev.34-156-128-236.sslip.io;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 503;
    }
}
